# -----------------------------------------------------------------------------
# Zero-trust local stack for Ollama:
# - Internal "backend" network is isolated from the internet.
# - Only the reverse proxy (nginx) is exposed to localhost.
# - mTLS (client certificates) + optional OIDC (oauth2-proxy).
# -----------------------------------------------------------------------------

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    # Bind only to the backend network; do NOT publish ports.
    networks:
      - backend
    expose:
      - "11434"
    environment:
      # Ollama binds to all interfaces inside the container;
      # we keep it unreachable from host by NOT mapping ports.
      OLLAMA_HOST: 0.0.0.0:11434
      # Restrict CORS to the proxy origin you expose (adjust to your hostname)
      OLLAMA_ORIGINS: "https://localhost"
    volumes:
      # Persistent encrypted model cache (encrypt the underlying disk/FS)
      - ollama-data:/root/.ollama:rw,noexec
      # Writable temp, but isolated
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1073741824  # 1 GiB
    # Security hardening
    security_opt:
      - no-new-privileges:true
      # Uncomment and provide a local seccomp profile if desired:
      # - seccomp=/opt/seccomp/default.json
    cap_drop:
      - ALL
    read_only: true     # Container FS is read-only
    # Provide only the directories that must be writable via volumes/tmpfs.
    ulimits:
      nproc: 4096
      nofile: 65536
    # Resource guards (Compose supports these keys for local Docker)
    mem_limit: "16g"
    cpus: "8.0"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    restart: unless-stopped
    # Optional: enable if you want OIDC/OAuth2 SSO. If you only want mTLS,
    # you can comment this service and related NGINX config.
    networks:
      - backend
      - egress
    # Use public DNS to avoid host resolver issues for OIDC discovery
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_UPSTREAMS: "file:///dev/null"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      # Verbose logging for troubleshooting
      OAUTH2_PROXY_LOG_LEVEL: "debug"
      OAUTH2_PROXY_REQUEST_LOGGING: "true"
      OAUTH2_PROXY_AUTH_LOGGING: "true"
      OAUTH2_PROXY_SILENCE_PING_LOGGING: "false"
      OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET}"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_REFRESH: "1h"
      OAUTH2_PROXY_COOKIE_EXPIRE: "8h"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      # Let oauth2-proxy infer redirect URL from incoming Host/headers so it works
      # on both localhost and api.localhost. Also allow both hosts for cookie domain/whitelist.
      # OAUTH2_PROXY_REDIRECT_URL removed on purpose.
      OAUTH2_PROXY_WHITELIST_DOMAINS: "localhost,api.localhost"
      OAUTH2_PROXY_COOKIE_DOMAINS: "localhost,api.localhost"
      OAUTH2_PROXY_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "${OIDC_ISSUER_URL}"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      # Cookie-based sessions (no Redis)
      OAUTH2_PROXY_SESSION_STORE_TYPE: "cookie"
      # Allow Authorization: Bearer <JWT> in place of cookie sessions on localhost API
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
    # No healthcheck: image is distroless (no shell/wget). Rely on startup logs and NGINX connectivity.

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - backend
      - egress
    ports:
      - "443:443"
    depends_on:
      ollama:
        condition: service_started
      oauth2-proxy:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount certs with filenames expected by nginx.conf
      - ./certs/server-cert.pem:/etc/nginx/tls/server.crt:ro
      - ./certs/server-key.pem:/etc/nginx/tls/server.key:ro
      - ./certs/ca-cert.pem:/etc/nginx/tls/ca.crt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --no-check-certificate -O- https://127.0.0.1/healthz >/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s


volumes:
  ollama-data:

networks:
  backend:
    driver: bridge
    internal: true
  egress:
    driver: bridge